#=====================API-docs scan base package==================================
api:
  doc:
    scan:
      base:
        package: com.tra.controller
    version: v0.0.1

#====Decided the configuration file through mvn packaged -P/-- params=============
spring:
  profiles:
    active: local