#====Decided the configuration file through mvn packaged -P/-- params=============
spring:
  profiles:
    active: local
  datasource:
    username: dyp
    password: 1234567890
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver

#==========================Spring log configuration===============================
logging:
  config: classpath:logback-boot.xml

#=====================API-docs scan base package==================================
api:
  doc:
    scan:
      base:
        package: com.tra.controller
    version: v0.0.1

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml